### ISSUE TITLE
Subs stuck on one side of the screen

### ISSUE THREAD

**Issue by kxti333** [chuyunshen/traditou#1]
The subs get stuck on one side of the screen but work on the other, just wondering if that is normal or not

**Comment by chuyunshen** [comment]
Hi, that doesn't sound very good. Can you provide a screenshot? Which website are you watching from and what show is it?

**Comment by kxti333** [comment]
I was watching Aller Simple on Novoo

The left side is where the subs got stuck and the right is where they
worked from the last -. the correct subs only showed up there

**Comment by chuyunshen** [comment]
Thanks! I see what you mean now: 
<img width="931" alt="Screenshot 2023-10-25 at 12 16 01 PM" src="https://github.com/chuyunshen/traditou/assets/44233890/91f81a97-d868-417b-877d-2a7a01499468">
I will fix it when I get a chance.

**Comment by chuyunshen** [comment]
@kxti333 Sorry about the delay! The bug is now fixed and should be reflected on the Chrome web store in a few days
